package uni.lars.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.declarative.Design;


/**
 * Created by uni on 8/19/16.
 */
@DesignRoot
public class MenuDesign extends HorizontalLayout {
    protected Button menuToggle;
    protected CssLayout menuItems;
    protected Button indexButton;
//    protected Label hostLabel;
    protected Button searchButton;
    protected Button esearchButton;
    protected Button conButton;
    protected Button xmppButton;

    public MenuDesign() {
        Design.read(this);
    }
}
